### ISSUE TITLE
Attempt to invoke virtual method 'io.chirp.connect.models.ChirpError io.chirp.connect.ChirpConnect.stop()' on a null object reference

### ISSUE THREAD

**Issue by shalin-jasani747** [chirp/chirp-connect-react-native#12]
Getting this error while trying to run the application on  Android with new SDK 

![screen shot 2018-09-02 at 11 50 36 pm](https://user-images.githubusercontent.com/13168588/44959392-11076b00-af0b-11e8-9736-e6e67afb1610.png)

Can anyone please help?

**Comment by joextodd** [comment]
@shalin-jasani747 it looks like `onHostPause` is being called before you have initialised a `chirpConnect` instance.

**Comment by shalin-jasani747** [comment]
Hi @dinuchiriac here is the full error log image

![screen shot 2018-09-05 at 10 36 48 pm](https://user-images.githubusercontent.com/39464564/45109213-7bfbb080-b15c-11e8-9a98-c5ead8e9a2a8.png)

**Comment by shalin-jasani747** [comment]
@joextodd Yes it is calling onHostPause at the time of intializing the application

**Comment by joextodd** [comment]
@shalin-jasani747 you can go ahead and edit [L275](https://github.com/chirp/chirp-connect-react-native/blob/1e3bbfc8896daa7ab558c3ae4dc555d8931b5b11/android/RCTChirpConnectModule.java#L275) of RCTChirpConnectModule.java, and check if `chirpConnect` has been initialised before calling stop.

However I am slightly confused as to why your activity is going into the background when initialising the application.
