### ISSUE TITLE
[onReceived] JNI NewObjectV called with pending exception java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by rajaishwary** [chirp/chirp-connect-react-native#18]
Facing the below crash on Received event. Please let me know if it's native issue or i am doing something wrong.
"react-native": "0.57.0"

JNI DETECTED ERROR IN APPLICATION: JNI NewObjectV called with pending exception java.lang.NullPointerException: Attempt to get length of null array
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #03 pc 0024e9bd  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+732)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #04 pc 0024ed33  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+58)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #06 pc 000d611f  /system/lib/libart.so (art::ScopedCheck::CheckThread(_JNIEnv*)+278)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #07 pc 000d4add  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::JniValueType*)+600)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #08 pc 000c7cfb  /system/lib/libart.so (art::CheckJNI::NewObjectV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+474)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #09 pc 000c7af7  /system/lib/libart.so (art::CheckJNI::NewObject(_JNIEnv*, _jclass*, _jmethodID*, ...)+30)
11-01 01:13:42.054 31528-31818/com.********* A/zygote: java_vm_ext.cc:534]   native: #10 pc 000d22bc  /data/app/com.*********-3R0JrB79741yQ7JA6oz7cA==/lib/arm/libgojni.so (Java_chirpconnect_SDK_processShortsInput+112)

**Comment by kostimarko** [comment]
Can you post your code?

**Comment by joextodd** [comment]
I think I see the problem here - the Android SDK will return a null payload on a decode failure. Will be posting a fix shortly
